image: maven:3.9.8-amazoncorretto-21

stages:
  - validate
  - compile
  - test
  - package
  - verify
  - install

anti-clutter-job:
  stage: validate
  script:
    - echo "Vérification qu'aucun fichier .class ne soit poussé sur le serveur"
    - CLUTTER=$(find . -name \*.class)
    - if [[ ! -z $CLUTTER ]]; then exit 1; fi
    - echo "Vérification qu'aucun fichier .jar ne soit poussé sur le serveur"
    - CLUTTER2=$(find . -name \*.jar)
    - if [[ ! -z $CLUTTER2 ]]; then exit 1; else exit 0; fi

validation-job:
  stage: validate
  script:
    - echo "Validation du projet Maven"
    - mvn clean validate -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -B
  only:
    - feature

compilation-job:
  stage: compile
  script:
    - echo "Compilation du projet"
    - mvn clean compile -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -B
  artifacts:
    paths:
      - target/
  only:
    - main

test-job:
  stage: test
  script:
    - echo "Exécution des tests unitaires"
    - mvn clean test -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -B
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml

package-job:
  stage: package
  script:
    - echo "Création du package du projet"
    - mvn clean package -DskipTests -Djacoco.skip=true -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -B
