@startuml

class Conway {
  + {static} main(args: String[])
  + createBoard(): ConwayBoard
}

interface Cell {
  + isStateSwitching(): Boolean
  + switchState()
}

interface Board {
  + printBoard()
}

interface Simulator {
  + simulate(board: ConwayBoard)
}

class ConwayCell {
  - neighbors: Cell[]
  + isStateSwitching(): Boolean
  + switchState()
}

class ConwayBoard {
  - cells: ConwayCell[][]
  + printBoard()
  + getNeighbors(cell: Cell): Cell[]
}

class ConwaySimulator {
  + simulate(board: ConwayBoard)
}

Conway *--> ConwayBoard
Conway *--> ConwaySimulator

Cell <|-- ConwayCell
Board <|-- ConwayBoard
Simulator <|-- ConwaySimulator

ConwayBoard *--> "1..*" ConwayCell
ConwaySimulator --> ConwayBoard

@enduml
