@startuml

class Conway {
  + {static} main(args: String[])
  + createBoard(): ConwayBoard
}

interface Cell {
  + isStateSwitching(): Boolean
  + switchState()
}

interface Board {
  + printBoard()
}

interface Simulator {
  + simulate(board: ConwayBoard)
}

interface GameArguments{
	+ loadArguments()
	+ getArguments(): GameData
}
abstract GameData{

}

class ConwayCell {
  - neighbors: Cell[]
  + isStateSwitching(): Boolean
  + switchState()
}

class ConwayBoard {
  - cells: ConwayCell[][]
  + printBoard()
  + getNeighbors(cell: Cell): Cell[]
}

class ConwaySimulator {
  + simulate(board: ConwayBoard)
}
class ConwayGameData{

}

class ConwayGameArguments{
	+ loadArguments()
	+ getArguments(): GameData
}

Conway *--> ConwayBoard
Conway *--> ConwaySimulator
Conway --> ConwayGameArguments
ConwayGameArguments *--> ConwayGameData
Cell <|-- ConwayCell
Board <|-- ConwayBoard
Simulator <|-- ConwaySimulator
GameArguments <|-- ConwayGameArguments
GameData <|-- ConwayGameData
ConwayBoard *--> "1..*" ConwayCell
ConwaySimulator --> ConwayBoard

@enduml
