@startuml

hide footbox
participant "Conway" as conway
[-> conway: initializeGame(args: String[])
activate conway
    create participant "ConwayGameArguments" as args
    conway -> args: loadArguments(args: String[])
    activate args
    args -> args: extractNumberOfIteration(args[1])
    args -> args: extractBoardStructure(args[0])
    args --> conway
    deactivate args
    create participant "ConwayBoard" as board
    conway -> board: initializeBoard(GameArguments args)
    activate board
    loop for each cell in boardStructure
        create participant "ConwayCell" as cell
        board -> cell: ConwayCell(Position position, CellState state)
        activate cell
        cell --> board
        deactivate cell
    end
    board --> conway:  
    deactivate board 
    [<-- conway:
    deactivate conway
    [-> conway: run()
    activate conway
    conway -> board: simulate()
    activate board
    loop for i = 0 to numberOfIterations
        board -> board: copy(): ConwayBoard
        activate board
        board --> board: ConwayBoard
        deactivate board
        loop for each cell in board
            board -> board: getNeighborStates(cell: Cell): List<CellState>
            activate board
            board --> board: List<CellState>
            deactivate board
            board -> cell: isStateSwitching(): boolean
            activate cell
            cell --> board: boolean
            deactivate cell
            alt if state is switching
                board -> cell: switchState()
                activate cell
                cell --> board
                deactivate cell
            end
        end
        board -> board: setBoard(newBoard: ConwayBoard)
        activate board
        board --> board 
        deactivate board
    end
    board --> conway:
    deactivate board
    conway -> board: printBoard()
    activate board
    board --> conway
    deactivate board
    [<-- conway:
deactivate conway

@enduml
